{
  "hash": "10fa82f2b219f7a690e1d471666b7728",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 1: Census Data Quality for Policy Decisions\"\nsubtitle: \"Evaluating Data Reliability for Algorithmic Decision-Making\"\nauthor: \"Angie Kwon\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\nexecute:\n  warning: false\n  message: false\n---\n\n# Assignment Overview\n\n## Scenario\n\nYou are a data analyst for the **Michigan Department of Human Services**. The department is considering implementing an algorithmic system to identify communities that should receive priority for social service funding and outreach programs. Your supervisor has asked you to evaluate the quality and reliability of available census data to inform this decision.\n\nDrawing on our Week 2 discussion of algorithmic bias, you need to assess not just what the data shows, but how reliable it is and what communities might be affected by data quality issues.\n\n## Learning Objectives\n\n- Apply dplyr functions to real census data for policy analysis\n- Evaluate data quality using margins of error \n- Connect technical analysis to algorithmic decision-making\n- Identify potential equity implications of data reliability issues\n- Create professional documentation for policy stakeholders\n\n## Submission Instructions\n\n**Submit by posting your updated portfolio link on Canvas.** Your assignment should be accessible at `your-portfolio-url/labs/lab_1/`\n\nMake sure to update your `_quarto.yml` navigation to include this assignment under an \"Labs\" menu.\n\n# Part 1: Portfolio Integration\n\nCreate this assignment in your portfolio repository under an `labs/lab_1/` folder structure. Update your navigation menu to include:\n\n```\n- text: Assignments\n  menu:\n    - href: labs/lab_1/your_file_name.qmd\n      text: \"Lab 1: Census Data Exploration\"\n```\nIf there is a special character like a colon, you need use double quote mark so that the quarto can identify this as text\n\n# Setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages (hint: you need tidycensus, tidyverse, and knitr)\n# install.packages(\"tidycensus\")\n# install.packages(\"tidyverse\")\n# install.packages(\"knitr\")\nlibrary(tidycensus)\nlibrary(tidyverse)\nlibrary(knitr)\n\n# Set your Census API key\n# census_api_key(\"eb283fc5f20283cf588e1f363afe8bc73cf9c354\", install = TRUE)\n\n# Choose your state for analysis - assign it to a variable called my_state\nmy_state <- \"Michigan\"\n```\n:::\n\n\n**State Selection:** I have chosen **Michigan** for this analysis because: I was born in Michigan, lived there until I was 6 and returned for high school.\n\n# Part 2: County-Level Resource Assessment\n\n## 2.1 Data Retrieval\n\n**Your Task:** Use `get_acs()` to retrieve county-level data for your chosen state.\n\n**Requirements:**\n- Geography: county level\n- Variables: median household income (B19013_001) and total population (B01003_001)  \n- Year: 2022\n- Survey: acs5\n- Output format: wide\n\n**Hint:** Remember to give your variables descriptive names using the `variables = c(name = \"code\")` syntax.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Write your get_acs() code here\nacsVariables <- c(med_HH_inc = \"B19013_001\", totpop = \"B01003_001\")\nMI_2022 <- get_acs(geography=\"county\", variables = acsVariables,\n                        state = \"MI\", survey = \"acs5\", year = 2022, output = \"wide\")\n\n# Clean the county names to remove state name and \"County\" \n# Hint: use mutate() with str_remove()\nMI_2022 <- MI_2022 %>%\n  mutate(NAME = str_remove(NAME, \" County, Michigan\"))\n\n# Display the first few rows\nglimpse(MI_2022)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 83\nColumns: 6\n$ GEOID       <chr> \"26001\", \"26003\", \"26005\", \"26007\", \"26009\", \"26011\", \"260…\n$ NAME        <chr> \"Alcona\", \"Alger\", \"Allegan\", \"Alpena\", \"Antrim\", \"Arenac\"…\n$ med_HH_incE <dbl> 50295, 55528, 75543, 49133, 68850, 53487, 51911, 75182, 57…\n$ med_HH_incM <dbl> 2243, 2912, 2369, 2119, 3115, 2018, 2904, 2704, 2395, 4258…\n$ totpopE     <dbl> 10238, 8866, 120189, 28911, 23662, 15031, 8245, 62581, 103…\n$ totpopM     <dbl> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…\n```\n\n\n:::\n:::\n\n\n## 2.2 Data Quality Assessment\n\n**Your Task:** Calculate margin of error percentages and create reliability categories.\n\n**Requirements:**\n- Calculate MOE percentage: (margin of error / estimate) * 100\n- Create reliability categories:\n  - High Confidence: MOE < 5%\n  - Moderate Confidence: MOE 5-10%  \n  - Low Confidence: MOE > 10%\n- Create a flag for unreliable estimates (MOE > 10%)\n\n**Hint:** Use `mutate()` with `case_when()` for the categories.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate MOE percentage and reliability categories using mutate()\n#without mutate()\n#MI_2022$MOE_per <- (MI_2022$med_HH_incM/MI_2022$med_HH_incE)*100\n\nMI_2022 <- MI_2022 %>%\n  mutate(MOE_per = (med_HH_incM/med_HH_incE)*100)\n\n# Create a summary showing count of counties in each reliability category\n# Hint: use count() and mutate() to add percentages\nMI_2022 <- MI_2022 %>% \n  mutate(reli_cat = case_when(MOE_per < 5 ~ 'High Confidence',\n                                   MOE_per > 10 ~ 'Low Confidence',\n                                   TRUE ~ 'Moderate Confidence'))\nreli_cat_freq <- MI_2022 %>%\n  count(reli_cat)\n```\n:::\n\n\n## 2.3 High Uncertainty Counties\n\n**Your Task:** Identify the 5 counties with the highest MOE percentages.\n\n**Requirements:**\n- Sort by MOE percentage (highest first)\n- Select the top 5 counties\n- Display: county name, median income, margin of error, MOE percentage, reliability category\n- Format as a professional table using `kable()`\n\n**Hint:** Use `arrange()`, `slice()`, and `select()` functions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create table of top 5 counties by MOE percentage\n#arrange(MI_2022, desc(MOE_per))\n#MOE_min <- MI_2022 %>% slice_min(MOE_per, n=5)\nMOE_max <- MI_2022 %>% slice_max(MOE_per, n=5)\n\n# Format as table with kable() - include appropriate column names and caption\nkable(MOE_max[, c(2,3,4,7,8)], \"simple\", col.names = c(\"Name\", \"Median Income\", \"Median Income Margin of Error\", \"Margin of Error Percentage\", \"Reliability\"), caption = \"Top 5 counties with the highest median income margins of error\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 5 counties with the highest median income margins of error\n\nName           Median Income   Median Income Margin of Error   Margin of Error Percentage  Reliability         \n------------  --------------  ------------------------------  ---------------------------  --------------------\nKeweenaw               55560                            7301                    13.140749  Low Confidence      \nSchoolcraft            55071                            6328                    11.490621  Low Confidence      \nGogebic                47913                            4766                     9.947196  Moderate Confidence \nOtsego                 62865                            5910                     9.401098  Moderate Confidence \nMontmorency            46345                            3796                     8.190743  Moderate Confidence \n\n\n:::\n\n```{.r .cell-code}\n#consequence bearing hardest on smallest counties?\npop_min <- MI_2022 %>% slice_min(totpopE, n=5)\nkable(pop_min[, c(2,5,3,4,7,8)], \"simple\", col.names = c(\"Name\", \"Total Population\", \"Median Income\", \"Median Income Margin of Error\", \"Margin of Error Percentage\", \"Reliability\"), caption = \"Top 5 counties with the lowest population\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 5 counties with the lowest population\n\nName           Total Population   Median Income   Median Income Margin of Error   Margin of Error Percentage  Reliability         \n------------  -----------------  --------------  ------------------------------  ---------------------------  --------------------\nKeweenaw                   2088           55560                            7301                    13.140749  Low Confidence      \nLuce                       5442           51015                            3742                     7.335097  Moderate Confidence \nOntonagon                  5862           48316                            3844                     7.955957  Moderate Confidence \nSchoolcraft                8062           55071                            6328                    11.490621  Low Confidence      \nBaraga                     8245           51911                            2904                     5.594190  Moderate Confidence \n\n\n:::\n:::\n\n\n**Data Quality Commentary:**\n\n[Write 2-3 sentences explaining what these results mean for algorithmic decision-making. Consider: Which counties might be poorly served by algorithms that rely on this income data? What factors might contribute to higher uncertainty?]\n\n# Part 3: Neighborhood-Level Analysis\n\n## 3.1 Focus Area Selection\n\n**Your Task:** Select 2-3 counties from your reliability analysis for detailed tract-level study.\n\n**Strategy:** Choose counties that represent different reliability levels (e.g., 1 high confidence, 1 moderate, 1 low confidence) to compare how data quality varies.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use filter() to select 2-3 counties from your county_reliability data\n# Store the selected counties in a variable called selected_counties\nfiltered_MI <- filter(MI_2022, NAME == \"Oakland\" | NAME == \"Mackinac\" | NAME == \"Keweenaw\")\n\n# Display the selected counties with their key characteristics\n# Show: county name, median income, MOE percentage, reliability category\nkable(filtered_MI[, c(2,3,7,8)], \"simple\", col.names = c(\"Name\", \"Median Income\", \"Margin of Error Percentage\", \"Reliability\"), caption = \"3 counties representing different data reliability levels\")\n```\n\n::: {.cell-output-display}\n\n\nTable: 3 counties representing different data reliability levels\n\nName        Median Income   Margin of Error Percentage  Reliability         \n---------  --------------  ---------------------------  --------------------\nKeweenaw            55560                    13.140749  Low Confidence      \nMackinac            60620                     5.679644  Moderate Confidence \nOakland             92620                     1.028935  High Confidence     \n\n\n:::\n:::\n\n\n**Comment on the output:** [write something :)]\n\n## 3.2 Tract-Level Demographics\n\n**Your Task:** Get demographic data for census tracts in your selected counties.\n\n**Requirements:**\n- Geography: tract level\n- Variables: white alone (B03002_003), Black/African American (B03002_004), Hispanic/Latino (B03002_012), total population (B03002_001)\n- Use the same state and year as before\n- Output format: wide\n- **Challenge:** You'll need county codes, not names. Look at the GEOID patterns in your county data for hints.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Define your race/ethnicity variables with descriptive names\nrace_eth_vars <- c(White = \"B03002_003\", Black = \"B03002_004\", Hisp_Lat = \"B03002_012\",\n                   Total_Pop = \"B03002_001\")\n\n# Use get_acs() to retrieve tract-level data\n# Hint: You may need to specify county codes in the county parameter\nrace_eth_2022 <- get_acs(geography=\"tract\", variables = race_eth_vars,\n                        state = \"MI\", county = c(083, 097, 125), \n                        survey = \"acs5\", year = 2022, output = \"wide\")\n\n# Calculate percentage of each group using mutate()\n# Create percentages for white, Black, and Hispanic populations\nrace_eth_2022 <- race_eth_2022 %>%\n  mutate(perW = (WhiteE/Total_PopE)*100,\n         perB = (BlackE/Total_PopE)*100,\n         perH = (Hisp_LatE/Total_PopE)*100)\n\n# Add readable tract and county name columns using str_extract() or similar\nrace_eth_2022 <- race_eth_2022 %>%\n  mutate(tract = str_extract(NAME, \"[0-9.]+\"),\n         NAME = str_extract(NAME, \"Oakland|Mackinac|Keweenaw\"))\n```\n:::\n\n\n## 3.3 Demographic Analysis\n\n**Your Task:** Analyze the demographic patterns in your selected areas.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Find the tract with the highest percentage of Hispanic/Latino residents\n# Hint: use arrange() and slice() to get the top tract\nhisp_max <- race_eth_2022 %>% slice_max(Hisp_LatE/Total_PopE, n=1)\n\n# Calculate average demographics by county using group_by() and summarize()\n# Show: number of tracts, average percentage for each racial/ethnic group\navg_demo <- race_eth_2022 %>%\n  group_by(NAME) %>%\n  summarize(avg_W_per = mean(perW, na.rm = TRUE), \n            avg_B_per = mean(perB, na.rm = TRUE),\n            avg_H_per = mean(perH, na.rm = TRUE),\n            count = n())\n\n# Create a nicely formatted table of your results using kable()\nkable(avg_demo[, c(1,5,2,3,4)], \"simple\", col.names = c(\"County\", \"Number of Tracts\", \"Average Percentage of White Residents\", \"Average Percentage of Black Residents\", \"Average Percentage of Hispanic Residents\"), caption = \"Average demographics of each county\")\n```\n\n::: {.cell-output-display}\n\n\nTable: Average demographics of each county\n\nCounty      Number of Tracts   Average Percentage of White Residents   Average Percentage of Black Residents   Average Percentage of Hispanic Residents\n---------  -----------------  --------------------------------------  --------------------------------------  -----------------------------------------\nKeweenaw                   3                                97.91467                                0.000000                                  0.7909875\nMackinac                   6                                74.24631                                3.418546                                  2.0344948\nOakland                  350                                69.26839                               14.115251                                  4.6550570\n\n\n:::\n:::\n\n\n# Part 4: Comprehensive Data Quality Evaluation\n\n## 4.1 MOE Analysis for Demographic Variables\n\n**Your Task:** Examine margins of error for demographic variables to see if some communities have less reliable data.\n\n**Requirements:**\n- Calculate MOE percentages for each demographic variable\n- Flag tracts where any demographic variable has MOE > 15%\n- Create summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate MOE percentages for white, Black, and Hispanic variables\n# Hint: use the same formula as before (margin/estimate * 100)\nrace_eth_2022 <- race_eth_2022 %>%\n  mutate(MOE_perW = (WhiteM/WhiteE)*100,\n         MOE_perB = (BlackM/BlackE)*100,\n         MOE_perH = (Hisp_LatM/Hisp_LatE)*100)\n# get rid of all infinites\nrace_eth_2022[sapply(race_eth_2022, is.infinite)] <- NA\n\n# Create a flag for tracts with high MOE on any demographic variable\n# Use logical operators (| for OR) in an ifelse() statement\n\n#misunderstood this as any variable, as in any of the 3 is high MOE\nrace_eth_2022 <- race_eth_2022 %>%\n  mutate(MOE_cat = ifelse(MOE_perW > 15 | MOE_perB > 15 | MOE_perH > 15, \n                          \"High MOE\", \"Low MOE\"))\nrace_eth_2022$MOE_cat[is.na(race_eth_2022$MOE_cat)] <- \"No Certainty\"\n\n#so second version where it's just black residents having high MOE\nrace_eth_2022 <- race_eth_2022 %>%\n  mutate(MOE_catB = ifelse(MOE_perB > 15,\n                          \"High Black MOE\", \"Low Black MOE\"))\nrace_eth_2022$MOE_catB[is.na(race_eth_2022$MOE_catB)] <- \"No Certainty\"\n\n# Create summary statistics showing how many tracts have data quality issues\ndata_qual_n <- race_eth_2022 %>%\n  group_by(MOE_cat) %>%\n  count(MOE_cat)\ndata_qual_n\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n# Groups:   MOE_cat [2]\n  MOE_cat          n\n  <chr>        <int>\n1 High MOE       351\n2 No Certainty     8\n```\n\n\n:::\n\n```{.r .cell-code}\ndata_qual_n_B <- race_eth_2022 %>%\n  group_by(MOE_catB) %>%\n  count(MOE_catB)\ndata_qual_n_B\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n# Groups:   MOE_catB [3]\n  MOE_catB           n\n  <chr>          <int>\n1 High Black MOE   322\n2 Low Black MOE      6\n3 No Certainty      31\n```\n\n\n:::\n:::\n\n\n## 4.2 Pattern Analysis\n\n**Your Task:** Investigate whether data quality problems are randomly distributed or concentrated in certain types of communities.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Group tracts by whether they have high MOE issues\n# Calculate average characteristics for each group:\n# - population size, demographic percentages\ndata_qual_examine <- race_eth_2022 %>%\n  group_by(MOE_cat) %>%\n  summarize(avg_pop = mean(Total_PopE, na.rm = TRUE), \n            avg_W_per = mean(perW, na.rm = TRUE),\n            avg_B_per = mean(perB, na.rm = TRUE),\n            avg_H_per = mean(perH, na.rm = TRUE),\n            count = n())\n\ndata_qual_W <- race_eth_2022 %>%\n  group_by(MOE_perW > 15) %>%\n  summarize(avg_pop = mean(Total_PopE, na.rm = TRUE), \n            avg_W_per = mean(perW, na.rm = TRUE),\n            avg_B_per = mean(perB, na.rm = TRUE),\n            avg_H_per = mean(perH, na.rm = TRUE),\n            count = n())\ndata_qual_B <- race_eth_2022 %>%\n  group_by(MOE_perB > 15) %>%\n  summarize(avg_pop = mean(Total_PopE, na.rm = TRUE), \n            avg_W_per = mean(perW, na.rm = TRUE),\n            avg_B_per = mean(perB, na.rm = TRUE),\n            avg_H_per = mean(perH, na.rm = TRUE),\n            count = n())\ndata_qual_H <- race_eth_2022 %>%\n  group_by(MOE_perH > 15) %>%\n  summarize(avg_pop = mean(Total_PopE, na.rm = TRUE), \n            avg_W_per = mean(perW, na.rm = TRUE),\n            avg_B_per = mean(perB, na.rm = TRUE),\n            avg_H_per = mean(perH, na.rm = TRUE),\n            count = n())\n\nrace_eth_2022 <- race_eth_2022 %>% \n  mutate(indv_MOE_cat = case_when(MOE_perW > 15 & MOE_perB > 15 & MOE_perH > 15 ~ 'All High MOE',\n                                  MOE_perW < 15 & MOE_perB < 15 & MOE_perH < 15 ~ 'All Low MOE',\n                                  MOE_perW > 15 & MOE_perB > 15 | MOE_perH > 15 ~ 'Two High MOE',\n                                  MOE_perW > 15 | MOE_perB > 15 & MOE_perH > 15 ~ 'Two High MOE',\n                                  MOE_perW > 15 & MOE_perH > 15 | MOE_perB > 15 ~ 'Two High MOE',\n                                  is.na(MOE_perW) | is.na(MOE_perH) | is.na(MOE_perB) ~ 'At least one NA',\n                                   TRUE ~ 'One High MOE'))\ndetail_MOE_cat <- race_eth_2022 %>%\n  group_by(indv_MOE_cat) %>%\n  summarize(avg_pop = mean(Total_PopE, na.rm = TRUE), \n            avg_W_per = mean(perW, na.rm = TRUE),\n            avg_B_per = mean(perB, na.rm = TRUE),\n            avg_H_per = mean(perH, na.rm = TRUE),\n            count = n())\n\n\n#just white residents having high MOE\nrace_eth_2022 <- race_eth_2022 %>%\n  mutate(MOE_catW = ifelse(MOE_perW > 15,\n                          \"High White MOE\", \"Low White MOE\"))\nrace_eth_2022$MOE_catW[is.na(race_eth_2022$MOE_catW)] <- \"No Certainty\"\n\ndata_qual_n_W <- race_eth_2022 %>%\n  group_by(MOE_catW) %>%\n  count(MOE_catW)\ndata_qual_n_W\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n# Groups:   MOE_catW [3]\n  MOE_catW           n\n  <chr>          <int>\n1 High White MOE   187\n2 Low White MOE    165\n3 No Certainty       7\n```\n\n\n:::\n\n```{.r .cell-code}\n#just hispanic residents having high MOE\nrace_eth_2022 <- race_eth_2022 %>%\n  mutate(MOE_catH = ifelse(MOE_perH > 15,\n                          \"High Hispanic MOE\", \"Low Hispanic MOE\"))\nrace_eth_2022$MOE_catH[is.na(race_eth_2022$MOE_catH)] <- \"No Certainty\"\n\ndata_qual_n_H <- race_eth_2022 %>%\n  group_by(MOE_catH) %>%\n  count(MOE_catH)\ndata_qual_n_H\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n# Groups:   MOE_catH [3]\n  MOE_catH              n\n  <chr>             <int>\n1 High Hispanic MOE   342\n2 Low Hispanic MOE      2\n3 No Certainty         15\n```\n\n\n:::\n\n```{.r .cell-code}\n# Use group_by() and summarize() to create this comparison\n# Create a professional table showing the patterns\nrace <- c(\"White\", \"Black\", \"Hispanic\")\nhigh_MOE_n <- c(187, 322, 342)\nlow_MOE_n <- c(165, 6, 2)\nno_certain_n <- c(7, 31, 15)\nrace_n_high_MOE <- data.frame(race, high_MOE_n, low_MOE_n, no_certain_n)\n\nrace_n_high_MOE <- race_n_high_MOE %>%\n  mutate(per_High = high_MOE_n/(high_MOE_n+low_MOE_n)*100)\nrace_n_high_MOE\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      race high_MOE_n low_MOE_n no_certain_n per_High\n1    White        187       165            7 53.12500\n2    Black        322         6           31 98.17073\n3 Hispanic        342         2           15 99.41860\n```\n\n\n:::\n:::\n\n\n**Pattern Analysis:** [Describe any patterns you observe. Do certain types of communities have less reliable data? What might explain this?]\n\n\n# Part 5: Policy Recommendations\n\n## 5.1 Analysis Integration and Professional Summary\n\n**Your Task:** Write an executive summary that integrates findings from all four analyses.\n\n**Executive Summary Requirements:**\n1. **Overall Pattern Identification**: What are the systematic patterns across all your analyses?\n2. **Equity Assessment**: Which communities face the greatest risk of algorithmic bias based on your findings?\n3. **Root Cause Analysis**: What underlying factors drive both data quality issues and bias risk?\n4. **Strategic Recommendations**: What should the Department implement to address these systematic issues?\n\n**Executive Summary:**\n\n[Your integrated 4-paragraph summary here]\n\n## 6.3 Specific Recommendations\n\n**Your Task:** Create a decision framework for algorithm implementation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a summary table using your county reliability data\n# Include: county name, median income, MOE percentage, reliability category\n\n# Add a new column with algorithm recommendations using case_when():\n# - High Confidence: \"Safe for algorithmic decisions\"\n# - Moderate Confidence: \"Use with caution - monitor outcomes\"  \n# - Low Confidence: \"Requires manual review or additional data\"\n\n# Format as a professional table with kable()\n```\n:::\n\n\n**Key Recommendations:**\n\n**Your Task:** Use your analysis results to provide specific guidance to the department.\n\n1. **Counties suitable for immediate algorithmic implementation:** [List counties with high confidence data and explain why they're appropriate]\n\n2. **Counties requiring additional oversight:** [List counties with moderate confidence data and describe what kind of monitoring would be needed]\n\n3. **Counties needing alternative approaches:** [List counties with low confidence data and suggest specific alternatives - manual review, additional surveys, etc.]\n\n## Questions for Further Investigation\n\n[List 2-3 questions that your analysis raised that you'd like to explore further in future assignments. Consider questions about spatial patterns, time trends, or other demographic factors.]\n\n# Technical Notes\n\n**Data Sources:** \n- U.S. Census Bureau, American Community Survey 2018-2022 5-Year Estimates\n- Retrieved via tidycensus R package on [date]\n\n**Reproducibility:** \n- All analysis conducted in R version [your version]\n- Census API key required for replication\n- Complete code and documentation available at: [your portfolio URL]\n\n**Methodology Notes:**\n[Describe any decisions you made about data processing, county selection, or analytical choices that might affect reproducibility]\n\n**Limitations:**\n[Note any limitations in your analysis - sample size issues, geographic scope, temporal factors, etc.]\n\n---\n\n## Submission Checklist\n\nBefore submitting your portfolio link on Canvas:\n\n- [ ] All code chunks run without errors\n- [ ] All \"[Fill this in]\" prompts have been completed\n- [ ] Tables are properly formatted and readable\n- [ ] Executive summary addresses all four required components\n- [ ] Portfolio navigation includes this assignment\n- [ ] Census API key is properly set \n- [ ] Document renders correctly to HTML\n\n**Remember:** Submit your portfolio URL on Canvas, not the file itself. Your assignment should be accessible at `your-portfolio-url/labs/lab_1/your_file_name.html`",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}