<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Angie Kwon">
<meta name="dcterms.date" content="2026-02-09">

<title>Lab 1: Census Data Quality for Policy Decisions – Angie Kwon - MUSA 5080 Portfolio</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5b4ad623e5705c0698d39aec6f10cf02.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Angie Kwon - MUSA 5080 Portfolio</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-labs" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Labs</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-labs">    
        <li>
    <a class="dropdown-item" href="../../labs/lab_0/lab0_template.html">
 <span class="dropdown-text">Lab 0: dplyr Basics</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../labs/lab_1/lab1.html">
 <span class="dropdown-text">Lab 1: Census Data Exploration</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#assignment-overview" id="toc-assignment-overview" class="nav-link active" data-scroll-target="#assignment-overview">Assignment Overview</a>
  <ul class="collapse">
  <li><a href="#scenario" id="toc-scenario" class="nav-link" data-scroll-target="#scenario">Scenario</a></li>
  <li><a href="#learning-objectives" id="toc-learning-objectives" class="nav-link" data-scroll-target="#learning-objectives">Learning Objectives</a></li>
  <li><a href="#submission-instructions" id="toc-submission-instructions" class="nav-link" data-scroll-target="#submission-instructions">Submission Instructions</a></li>
  </ul></li>
  <li><a href="#part-1-portfolio-integration" id="toc-part-1-portfolio-integration" class="nav-link" data-scroll-target="#part-1-portfolio-integration">Part 1: Portfolio Integration</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#part-2-county-level-resource-assessment" id="toc-part-2-county-level-resource-assessment" class="nav-link" data-scroll-target="#part-2-county-level-resource-assessment">Part 2: County-Level Resource Assessment</a>
  <ul class="collapse">
  <li><a href="#data-retrieval" id="toc-data-retrieval" class="nav-link" data-scroll-target="#data-retrieval">2.1 Data Retrieval</a></li>
  <li><a href="#data-quality-assessment" id="toc-data-quality-assessment" class="nav-link" data-scroll-target="#data-quality-assessment">2.2 Data Quality Assessment</a></li>
  <li><a href="#high-uncertainty-counties" id="toc-high-uncertainty-counties" class="nav-link" data-scroll-target="#high-uncertainty-counties">2.3 High Uncertainty Counties</a></li>
  </ul></li>
  <li><a href="#part-3-neighborhood-level-analysis" id="toc-part-3-neighborhood-level-analysis" class="nav-link" data-scroll-target="#part-3-neighborhood-level-analysis">Part 3: Neighborhood-Level Analysis</a>
  <ul class="collapse">
  <li><a href="#focus-area-selection" id="toc-focus-area-selection" class="nav-link" data-scroll-target="#focus-area-selection">3.1 Focus Area Selection</a></li>
  <li><a href="#tract-level-demographics" id="toc-tract-level-demographics" class="nav-link" data-scroll-target="#tract-level-demographics">3.2 Tract-Level Demographics</a></li>
  <li><a href="#demographic-analysis" id="toc-demographic-analysis" class="nav-link" data-scroll-target="#demographic-analysis">3.3 Demographic Analysis</a></li>
  </ul></li>
  <li><a href="#part-4-comprehensive-data-quality-evaluation" id="toc-part-4-comprehensive-data-quality-evaluation" class="nav-link" data-scroll-target="#part-4-comprehensive-data-quality-evaluation">Part 4: Comprehensive Data Quality Evaluation</a>
  <ul class="collapse">
  <li><a href="#moe-analysis-for-demographic-variables" id="toc-moe-analysis-for-demographic-variables" class="nav-link" data-scroll-target="#moe-analysis-for-demographic-variables">4.1 MOE Analysis for Demographic Variables</a></li>
  <li><a href="#pattern-analysis" id="toc-pattern-analysis" class="nav-link" data-scroll-target="#pattern-analysis">4.2 Pattern Analysis</a></li>
  </ul></li>
  <li><a href="#part-5-policy-recommendations" id="toc-part-5-policy-recommendations" class="nav-link" data-scroll-target="#part-5-policy-recommendations">Part 5: Policy Recommendations</a>
  <ul class="collapse">
  <li><a href="#analysis-integration-and-professional-summary" id="toc-analysis-integration-and-professional-summary" class="nav-link" data-scroll-target="#analysis-integration-and-professional-summary">5.1 Analysis Integration and Professional Summary</a></li>
  <li><a href="#specific-recommendations" id="toc-specific-recommendations" class="nav-link" data-scroll-target="#specific-recommendations">6.3 Specific Recommendations</a></li>
  <li><a href="#questions-for-further-investigation" id="toc-questions-for-further-investigation" class="nav-link" data-scroll-target="#questions-for-further-investigation">Questions for Further Investigation</a></li>
  </ul></li>
  <li><a href="#technical-notes" id="toc-technical-notes" class="nav-link" data-scroll-target="#technical-notes">Technical Notes</a>
  <ul class="collapse">
  <li><a href="#submission-checklist" id="toc-submission-checklist" class="nav-link" data-scroll-target="#submission-checklist">Submission Checklist</a></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 1: Census Data Quality for Policy Decisions</h1>
<p class="subtitle lead">Evaluating Data Reliability for Algorithmic Decision-Making</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Angie Kwon </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 9, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="assignment-overview" class="level1">
<h1>Assignment Overview</h1>
<section id="scenario" class="level2">
<h2 class="anchored" data-anchor-id="scenario">Scenario</h2>
<p>You are a data analyst for the <strong>Michigan Department of Human Services</strong>. The department is considering implementing an algorithmic system to identify communities that should receive priority for social service funding and outreach programs. Your supervisor has asked you to evaluate the quality and reliability of available census data to inform this decision.</p>
<p>Drawing on our Week 2 discussion of algorithmic bias, you need to assess not just what the data shows, but how reliable it is and what communities might be affected by data quality issues.</p>
</section>
<section id="learning-objectives" class="level2">
<h2 class="anchored" data-anchor-id="learning-objectives">Learning Objectives</h2>
<ul>
<li>Apply dplyr functions to real census data for policy analysis</li>
<li>Evaluate data quality using margins of error</li>
<li>Connect technical analysis to algorithmic decision-making</li>
<li>Identify potential equity implications of data reliability issues</li>
<li>Create professional documentation for policy stakeholders</li>
</ul>
</section>
<section id="submission-instructions" class="level2">
<h2 class="anchored" data-anchor-id="submission-instructions">Submission Instructions</h2>
<p><strong>Submit by posting your updated portfolio link on Canvas.</strong> Your assignment should be accessible at <code>your-portfolio-url/labs/lab_1/</code></p>
<p>Make sure to update your <code>_quarto.yml</code> navigation to include this assignment under an “Labs” menu.</p>
</section>
</section>
<section id="part-1-portfolio-integration" class="level1">
<h1>Part 1: Portfolio Integration</h1>
<p>Create this assignment in your portfolio repository under an <code>labs/lab_1/</code> folder structure. Update your navigation menu to include:</p>
<pre><code>- text: Assignments
  menu:
    - href: labs/lab_1/your_file_name.qmd
      text: "Lab 1: Census Data Exploration"</code></pre>
<p>If there is a special character like a colon, you need use double quote mark so that the quarto can identify this as text</p>
</section>
<section id="setup" class="level1">
<h1>Setup</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required packages (hint: you need tidycensus, tidyverse, and knitr)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("tidycensus")</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("tidyverse")</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("knitr")</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidycensus)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Set your Census API key</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># census_api_key("eb283fc5f20283cf588e1f363afe8bc73cf9c354", install = TRUE)</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose your state for analysis - assign it to a variable called my_state</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>my_state <span class="ot">&lt;-</span> <span class="st">"Michigan"</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>State Selection:</strong> I have chosen <strong>Michigan</strong> for this analysis because: I was born in Michigan, lived there until I was 6 and returned for high school.</p>
</section>
<section id="part-2-county-level-resource-assessment" class="level1">
<h1>Part 2: County-Level Resource Assessment</h1>
<section id="data-retrieval" class="level2">
<h2 class="anchored" data-anchor-id="data-retrieval">2.1 Data Retrieval</h2>
<p><strong>Your Task:</strong> Use <code>get_acs()</code> to retrieve county-level data for your chosen state.</p>
<p><strong>Requirements:</strong> - Geography: county level - Variables: median household income (B19013_001) and total population (B01003_001)<br>
- Year: 2022 - Survey: acs5 - Output format: wide</p>
<p><strong>Hint:</strong> Remember to give your variables descriptive names using the <code>variables = c(name = "code")</code> syntax.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Write your get_acs() code here</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>acsVariables <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">med_HH_inc =</span> <span class="st">"B19013_001"</span>, <span class="at">totpop =</span> <span class="st">"B01003_001"</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>MI_2022 <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(<span class="at">geography=</span><span class="st">"county"</span>, <span class="at">variables =</span> acsVariables,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">state =</span> <span class="st">"MI"</span>, <span class="at">survey =</span> <span class="st">"acs5"</span>, <span class="at">year =</span> <span class="dv">2022</span>, <span class="at">output =</span> <span class="st">"wide"</span>)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Clean the county names to remove state name and "County" </span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use mutate() with str_remove()</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>MI_2022 <span class="ot">&lt;-</span> MI_2022 <span class="sc">%&gt;%</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">NAME =</span> <span class="fu">str_remove</span>(NAME, <span class="st">" County, Michigan"</span>))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the first few rows</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(MI_2022)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 83
Columns: 6
$ GEOID       &lt;chr&gt; "26001", "26003", "26005", "26007", "26009", "26011", "260…
$ NAME        &lt;chr&gt; "Alcona", "Alger", "Allegan", "Alpena", "Antrim", "Arenac"…
$ med_HH_incE &lt;dbl&gt; 50295, 55528, 75543, 49133, 68850, 53487, 51911, 75182, 57…
$ med_HH_incM &lt;dbl&gt; 2243, 2912, 2369, 2119, 3115, 2018, 2904, 2704, 2395, 4258…
$ totpopE     &lt;dbl&gt; 10238, 8866, 120189, 28911, 23662, 15031, 8245, 62581, 103…
$ totpopM     &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA…</code></pre>
</div>
</div>
</section>
<section id="data-quality-assessment" class="level2">
<h2 class="anchored" data-anchor-id="data-quality-assessment">2.2 Data Quality Assessment</h2>
<p><strong>Your Task:</strong> Calculate margin of error percentages and create reliability categories.</p>
<p><strong>Requirements:</strong> - Calculate MOE percentage: (margin of error / estimate) * 100 - Create reliability categories: - High Confidence: MOE &lt; 5% - Moderate Confidence: MOE 5-10%<br>
- Low Confidence: MOE &gt; 10% - Create a flag for unreliable estimates (MOE &gt; 10%)</p>
<p><strong>Hint:</strong> Use <code>mutate()</code> with <code>case_when()</code> for the categories.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentage and reliability categories using mutate()</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co">#without mutate()</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">#MI_2022$MOE_per &lt;- (MI_2022$med_HH_incM/MI_2022$med_HH_incE)*100</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>MI_2022 <span class="ot">&lt;-</span> MI_2022 <span class="sc">%&gt;%</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">MOE_per =</span> (med_HH_incM<span class="sc">/</span>med_HH_incE)<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary showing count of counties in each reliability category</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use count() and mutate() to add percentages</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>MI_2022 <span class="ot">&lt;-</span> MI_2022 <span class="sc">%&gt;%</span> </span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">reli_cat =</span> <span class="fu">case_when</span>(MOE_per <span class="sc">&lt;</span> <span class="dv">5</span> <span class="sc">~</span> <span class="st">'High Confidence'</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>                                   MOE_per <span class="sc">&gt;</span> <span class="dv">10</span> <span class="sc">~</span> <span class="st">'Low Confidence'</span>,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>                                   <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">'Moderate Confidence'</span>))</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>reli_cat_freq <span class="ot">&lt;-</span> MI_2022 <span class="sc">%&gt;%</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(reli_cat)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>reli_cat_freq</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  reli_cat                n
  &lt;chr&gt;               &lt;int&gt;
1 High Confidence        56
2 Low Confidence          2
3 Moderate Confidence    25</code></pre>
</div>
</div>
</section>
<section id="high-uncertainty-counties" class="level2">
<h2 class="anchored" data-anchor-id="high-uncertainty-counties">2.3 High Uncertainty Counties</h2>
<p><strong>Your Task:</strong> Identify the 5 counties with the highest MOE percentages.</p>
<p><strong>Requirements:</strong> - Sort by MOE percentage (highest first) - Select the top 5 counties - Display: county name, median income, margin of error, MOE percentage, reliability category - Format as a professional table using <code>kable()</code></p>
<p><strong>Hint:</strong> Use <code>arrange()</code>, <code>slice()</code>, and <code>select()</code> functions.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create table of top 5 counties by MOE percentage</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#arrange(MI_2022, desc(MOE_per))</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co">#MOE_min &lt;- MI_2022 %&gt;% slice_min(MOE_per, n=5)</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>MOE_max <span class="ot">&lt;-</span> MI_2022 <span class="sc">%&gt;%</span> <span class="fu">slice_max</span>(MOE_per, <span class="at">n=</span><span class="dv">5</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>MOE_max</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 5 × 8
  GEOID NAME        med_HH_incE med_HH_incM totpopE totpopM MOE_per reli_cat    
  &lt;chr&gt; &lt;chr&gt;             &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;       
1 26083 Keweenaw          55560        7301    2088      NA   13.1  Low Confide…
2 26153 Schoolcraft       55071        6328    8062      NA   11.5  Low Confide…
3 26053 Gogebic           47913        4766   14597      NA    9.95 Moderate Co…
4 26137 Otsego            62865        5910   25221      NA    9.40 Moderate Co…
5 26119 Montmorency       46345        3796    9261      NA    8.19 Moderate Co…</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Format as table with kable() - include appropriate column names and caption</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(MOE_max[, <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">8</span>)], <span class="st">"simple"</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Name"</span>, <span class="st">"Median Income"</span>, <span class="st">"Median Income Margin of Error"</span>, <span class="st">"Margin of Error Percentage"</span>, <span class="st">"Reliability"</span>), <span class="at">caption =</span> <span class="st">"Top 5 counties with the highest median income margins of error"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 counties with the highest median income margins of error</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">Median Income Margin of Error</th>
<th style="text-align: right;">Margin of Error Percentage</th>
<th style="text-align: left;">Reliability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Keweenaw</td>
<td style="text-align: right;">55560</td>
<td style="text-align: right;">7301</td>
<td style="text-align: right;">13.140749</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Schoolcraft</td>
<td style="text-align: right;">55071</td>
<td style="text-align: right;">6328</td>
<td style="text-align: right;">11.490621</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gogebic</td>
<td style="text-align: right;">47913</td>
<td style="text-align: right;">4766</td>
<td style="text-align: right;">9.947196</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Otsego</td>
<td style="text-align: right;">62865</td>
<td style="text-align: right;">5910</td>
<td style="text-align: right;">9.401098</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Montmorency</td>
<td style="text-align: right;">46345</td>
<td style="text-align: right;">3796</td>
<td style="text-align: right;">8.190743</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co">#consequence bearing hardest on smallest counties?</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>pop_min <span class="ot">&lt;-</span> MI_2022 <span class="sc">%&gt;%</span> <span class="fu">slice_min</span>(totpopE, <span class="at">n=</span><span class="dv">5</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(pop_min[, <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">7</span>,<span class="dv">8</span>)], <span class="st">"simple"</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Name"</span>, <span class="st">"Total Population"</span>, <span class="st">"Median Income"</span>, <span class="st">"Median Income Margin of Error"</span>, <span class="st">"Margin of Error Percentage"</span>, <span class="st">"Reliability"</span>), <span class="at">caption =</span> <span class="st">"Top 5 counties with the lowest population"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Top 5 counties with the lowest population</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: right;">Total Population</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">Median Income Margin of Error</th>
<th style="text-align: right;">Margin of Error Percentage</th>
<th style="text-align: left;">Reliability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Keweenaw</td>
<td style="text-align: right;">2088</td>
<td style="text-align: right;">55560</td>
<td style="text-align: right;">7301</td>
<td style="text-align: right;">13.140749</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Luce</td>
<td style="text-align: right;">5442</td>
<td style="text-align: right;">51015</td>
<td style="text-align: right;">3742</td>
<td style="text-align: right;">7.335097</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ontonagon</td>
<td style="text-align: right;">5862</td>
<td style="text-align: right;">48316</td>
<td style="text-align: right;">3844</td>
<td style="text-align: right;">7.955957</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Schoolcraft</td>
<td style="text-align: right;">8062</td>
<td style="text-align: right;">55071</td>
<td style="text-align: right;">6328</td>
<td style="text-align: right;">11.490621</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Baraga</td>
<td style="text-align: right;">8245</td>
<td style="text-align: right;">51911</td>
<td style="text-align: right;">2904</td>
<td style="text-align: right;">5.594190</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Data Quality Commentary:</strong></p>
<p>These results show that even with a government-wide survey, there are very high margins of error, which have policy implications, where these counties may be over- or underestimated in various variables. In this instance, the counties with higher margins of error may be overestimated as more affluent than they actually are, which may lead to them not receiving the aid or funding they need, or they might be underestimated as less wealthy than they actually are, which may lead to resources being needlessly diverted to them, when in fact others need them more. The second table shows that the population size may have at least some effect, since the two counties with “Low Confidence” are both in the top 5 smallest counties in Michigan.</p>
</section>
</section>
<section id="part-3-neighborhood-level-analysis" class="level1">
<h1>Part 3: Neighborhood-Level Analysis</h1>
<section id="focus-area-selection" class="level2">
<h2 class="anchored" data-anchor-id="focus-area-selection">3.1 Focus Area Selection</h2>
<p><strong>Your Task:</strong> Select 2-3 counties from your reliability analysis for detailed tract-level study.</p>
<p><strong>Strategy:</strong> Choose counties that represent different reliability levels (e.g., 1 high confidence, 1 moderate, 1 low confidence) to compare how data quality varies.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use filter() to select 2-3 counties from your county_reliability data</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Store the selected counties in a variable called selected_counties</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>filtered_MI <span class="ot">&lt;-</span> <span class="fu">filter</span>(MI_2022, NAME <span class="sc">==</span> <span class="st">"Oakland"</span> <span class="sc">|</span> NAME <span class="sc">==</span> <span class="st">"Mackinac"</span> <span class="sc">|</span> NAME <span class="sc">==</span> <span class="st">"Keweenaw"</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the selected counties with their key characteristics</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Show: county name, median income, MOE percentage, reliability category</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(filtered_MI[, <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">7</span>,<span class="dv">8</span>)], <span class="st">"simple"</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Name"</span>, <span class="st">"Median Income"</span>, <span class="st">"Margin of Error Percentage"</span>, <span class="st">"Reliability"</span>), <span class="at">caption =</span> <span class="st">"3 counties representing different data reliability levels"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>3 counties representing different data reliability levels</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: right;">Median Income</th>
<th style="text-align: right;">Margin of Error Percentage</th>
<th style="text-align: left;">Reliability</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Keweenaw</td>
<td style="text-align: right;">55560</td>
<td style="text-align: right;">13.140749</td>
<td style="text-align: left;">Low Confidence</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mackinac</td>
<td style="text-align: right;">60620</td>
<td style="text-align: right;">5.679644</td>
<td style="text-align: left;">Moderate Confidence</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oakland</td>
<td style="text-align: right;">92620</td>
<td style="text-align: right;">1.028935</td>
<td style="text-align: left;">High Confidence</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Comment on the output:</strong> The wide range of the margins of error is quite intersting, as they all come from one state, and presumably they try to draw county lines to be as representative as possible. Of course it can’t always be helped, but it’s interesting to see regardless. Also, Oakland county is where I grew up!</p>
</section>
<section id="tract-level-demographics" class="level2">
<h2 class="anchored" data-anchor-id="tract-level-demographics">3.2 Tract-Level Demographics</h2>
<p><strong>Your Task:</strong> Get demographic data for census tracts in your selected counties.</p>
<p><strong>Requirements:</strong> - Geography: tract level - Variables: white alone (B03002_003), Black/African American (B03002_004), Hispanic/Latino (B03002_012), total population (B03002_001) - Use the same state and year as before - Output format: wide - <strong>Challenge:</strong> You’ll need county codes, not names. Look at the GEOID patterns in your county data for hints.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define your race/ethnicity variables with descriptive names</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>race_eth_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="at">White =</span> <span class="st">"B03002_003"</span>, <span class="at">Black =</span> <span class="st">"B03002_004"</span>, <span class="at">Hisp_Lat =</span> <span class="st">"B03002_012"</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">Total_Pop =</span> <span class="st">"B03002_001"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Use get_acs() to retrieve tract-level data</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: You may need to specify county codes in the county parameter</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>race_eth_2022 <span class="ot">&lt;-</span> <span class="fu">get_acs</span>(<span class="at">geography=</span><span class="st">"tract"</span>, <span class="at">variables =</span> race_eth_vars,</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>                        <span class="at">state =</span> <span class="st">"MI"</span>, <span class="at">county =</span> <span class="fu">c</span>(<span class="dv">083</span>, <span class="dv">097</span>, <span class="dv">125</span>), </span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>                        <span class="at">survey =</span> <span class="st">"acs5"</span>, <span class="at">year =</span> <span class="dv">2022</span>, <span class="at">output =</span> <span class="st">"wide"</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate percentage of each group using mutate()</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Create percentages for white, Black, and Hispanic populations</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>race_eth_2022 <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">perW =</span> (WhiteE<span class="sc">/</span>Total_PopE)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">perB =</span> (BlackE<span class="sc">/</span>Total_PopE)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>         <span class="at">perH =</span> (Hisp_LatE<span class="sc">/</span>Total_PopE)<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Add readable tract and county name columns using str_extract() or similar</span></span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>race_eth_2022 <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">tract =</span> <span class="fu">str_extract</span>(NAME, <span class="st">"[0-9.]+"</span>),</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>         <span class="at">NAME =</span> <span class="fu">str_extract</span>(NAME, <span class="st">"Oakland|Mackinac|Keweenaw"</span>))</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>race_eth_2022</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 359 × 14
   GEOID       NAME   WhiteE WhiteM BlackE BlackM Hisp_LatE Hisp_LatM Total_PopE
   &lt;chr&gt;       &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1 26083000100 Kewee…   1999      6      0     11        33         4       2086
 2 26083980100 Kewee…      2      1      0     11         0        11          2
 3 26083990100 Kewee…      0     11      0     11         0        11          0
 4 26097950100 Macki…   1536    238      0     11         0        11       1594
 5 26097950200 Macki…   1858    216      0     11        49        42       2399
 6 26097950300 Macki…   1485    185      3      4        13        12       1761
 7 26097950400 Macki…   1788    187    141    107       115        59       2900
 8 26097950500 Macki…   1126    142    264    119        75        42       2189
 9 26097990000 Macki…      0     11      0     11         0        11          0
10 26125120000 Oakla…   2910    279     20     21        20        24       3074
# ℹ 349 more rows
# ℹ 5 more variables: Total_PopM &lt;dbl&gt;, perW &lt;dbl&gt;, perB &lt;dbl&gt;, perH &lt;dbl&gt;,
#   tract &lt;chr&gt;</code></pre>
</div>
</div>
</section>
<section id="demographic-analysis" class="level2">
<h2 class="anchored" data-anchor-id="demographic-analysis">3.3 Demographic Analysis</h2>
<p><strong>Your Task:</strong> Analyze the demographic patterns in your selected areas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the tract with the highest percentage of Hispanic/Latino residents</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use arrange() and slice() to get the top tract</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>hisp_max <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span> <span class="fu">slice_max</span>(Hisp_LatE<span class="sc">/</span>Total_PopE, <span class="at">n=</span><span class="dv">1</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average demographics by county using group_by() and summarize()</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Show: number of tracts, average percentage for each racial/ethnic group</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>avg_demo <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(NAME) <span class="sc">%&gt;%</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_W_per =</span> <span class="fu">mean</span>(perW, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_B_per =</span> <span class="fu">mean</span>(perB, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_H_per =</span> <span class="fu">mean</span>(perH, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>            <span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a nicely formatted table of your results using kable()</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(avg_demo[, <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">5</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>)], <span class="st">"simple"</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Number of Tracts"</span>, <span class="st">"Average Percentage of White Residents"</span>, <span class="st">"Average Percentage of Black Residents"</span>, <span class="st">"Average Percentage of Hispanic Residents"</span>), <span class="at">caption =</span> <span class="st">"Average demographics of each county"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Average demographics of each county</caption>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Number of Tracts</th>
<th style="text-align: right;">Average Percentage of White Residents</th>
<th style="text-align: right;">Average Percentage of Black Residents</th>
<th style="text-align: right;">Average Percentage of Hispanic Residents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Keweenaw</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">97.91467</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">0.7909875</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mackinac</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">74.24631</td>
<td style="text-align: right;">3.418546</td>
<td style="text-align: right;">2.0344948</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oakland</td>
<td style="text-align: right;">350</td>
<td style="text-align: right;">69.26839</td>
<td style="text-align: right;">14.115251</td>
<td style="text-align: right;">4.6550570</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="part-4-comprehensive-data-quality-evaluation" class="level1">
<h1>Part 4: Comprehensive Data Quality Evaluation</h1>
<section id="moe-analysis-for-demographic-variables" class="level2">
<h2 class="anchored" data-anchor-id="moe-analysis-for-demographic-variables">4.1 MOE Analysis for Demographic Variables</h2>
<p><strong>Your Task:</strong> Examine margins of error for demographic variables to see if some communities have less reliable data.</p>
<p><strong>Requirements:</strong> - Calculate MOE percentages for each demographic variable - Flag tracts where any demographic variable has MOE &gt; 15% - Create summary statistics</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate MOE percentages for white, Black, and Hispanic variables</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Hint: use the same formula as before (margin/estimate * 100)</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>race_eth_2022 <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">MOE_perW =</span> (WhiteM<span class="sc">/</span>WhiteE)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">MOE_perB =</span> (BlackM<span class="sc">/</span>BlackE)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">MOE_perH =</span> (Hisp_LatM<span class="sc">/</span>Hisp_LatE)<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># get rid of all infinites</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>race_eth_2022[<span class="fu">sapply</span>(race_eth_2022, is.infinite)] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a flag for tracts with high MOE on any demographic variable</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Use logical operators (| for OR) in an ifelse() statement</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="co">#misunderstood this as any variable, as in any of the 3 is high MOE</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>race_eth_2022 <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">MOE_cat =</span> <span class="fu">ifelse</span>(MOE_perW <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">|</span> MOE_perB <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">|</span> MOE_perH <span class="sc">&gt;</span> <span class="dv">15</span>, </span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"High MOE"</span>, <span class="st">"Low MOE"</span>))</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>race_eth_2022<span class="sc">$</span>MOE_cat[<span class="fu">is.na</span>(race_eth_2022<span class="sc">$</span>MOE_cat)] <span class="ot">&lt;-</span> <span class="st">"No Certainty"</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="co">#so second version where it's just black residents having high MOE</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>race_eth_2022 <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">MOE_catB =</span> <span class="fu">ifelse</span>(MOE_perB <span class="sc">&gt;</span> <span class="dv">15</span>,</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"High Black MOE"</span>, <span class="st">"Low Black MOE"</span>))</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>race_eth_2022<span class="sc">$</span>MOE_catB[<span class="fu">is.na</span>(race_eth_2022<span class="sc">$</span>MOE_catB)] <span class="ot">&lt;-</span> <span class="st">"No Certainty"</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>race_eth_2022</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 359 × 19
   GEOID       NAME   WhiteE WhiteM BlackE BlackM Hisp_LatE Hisp_LatM Total_PopE
   &lt;chr&gt;       &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1 26083000100 Kewee…   1999      6      0     11        33         4       2086
 2 26083980100 Kewee…      2      1      0     11         0        11          2
 3 26083990100 Kewee…      0     11      0     11         0        11          0
 4 26097950100 Macki…   1536    238      0     11         0        11       1594
 5 26097950200 Macki…   1858    216      0     11        49        42       2399
 6 26097950300 Macki…   1485    185      3      4        13        12       1761
 7 26097950400 Macki…   1788    187    141    107       115        59       2900
 8 26097950500 Macki…   1126    142    264    119        75        42       2189
 9 26097990000 Macki…      0     11      0     11         0        11          0
10 26125120000 Oakla…   2910    279     20     21        20        24       3074
# ℹ 349 more rows
# ℹ 10 more variables: Total_PopM &lt;dbl&gt;, perW &lt;dbl&gt;, perB &lt;dbl&gt;, perH &lt;dbl&gt;,
#   tract &lt;chr&gt;, MOE_perW &lt;dbl&gt;, MOE_perB &lt;dbl&gt;, MOE_perH &lt;dbl&gt;, MOE_cat &lt;chr&gt;,
#   MOE_catB &lt;chr&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create summary statistics showing how many tracts have data quality issues</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>data_qual_n <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(MOE_cat) <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(MOE_cat)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>data_qual_n</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
# Groups:   MOE_cat [2]
  MOE_cat          n
  &lt;chr&gt;        &lt;int&gt;
1 High MOE       351
2 No Certainty     8</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>data_qual_n_B <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(MOE_catB) <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(MOE_catB)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>data_qual_n_B</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
# Groups:   MOE_catB [3]
  MOE_catB           n
  &lt;chr&gt;          &lt;int&gt;
1 High Black MOE   322
2 Low Black MOE      6
3 No Certainty      31</code></pre>
</div>
</div>
</section>
<section id="pattern-analysis" class="level2">
<h2 class="anchored" data-anchor-id="pattern-analysis">4.2 Pattern Analysis</h2>
<p><strong>Your Task:</strong> Investigate whether data quality problems are randomly distributed or concentrated in certain types of communities.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Group tracts by whether they have high MOE issues</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate average characteristics for each group:</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="co"># - population size, demographic percentages</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>data_qual_examine <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(MOE_cat) <span class="sc">%&gt;%</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_pop =</span> <span class="fu">mean</span>(Total_PopE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_W_per =</span> <span class="fu">mean</span>(perW, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_B_per =</span> <span class="fu">mean</span>(perB, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_H_per =</span> <span class="fu">mean</span>(perH, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>data_qual_examine</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
  MOE_cat      avg_pop avg_W_per avg_B_per avg_H_per count
  &lt;chr&gt;          &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;
1 High MOE       3656.      69.4      13.9      4.60   351
2 No Certainty    261.      95.8       0        1.58     8</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>data_qual_W <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(MOE_perW <span class="sc">&gt;</span> <span class="dv">15</span>) <span class="sc">%&gt;%</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_pop =</span> <span class="fu">mean</span>(Total_PopE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_W_per =</span> <span class="fu">mean</span>(perW, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_B_per =</span> <span class="fu">mean</span>(perB, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_H_per =</span> <span class="fu">mean</span>(perH, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>data_qual_W</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  `MOE_perW &gt; 15` avg_pop avg_W_per avg_B_per avg_H_per count
  &lt;lgl&gt;             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;
1 FALSE             3834.      81.8      4.01      3.86   165
2 TRUE              3489.      58.7     22.6       5.25   187
3 NA                   0      NaN      NaN       NaN        7</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>data_qual_B <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(MOE_perB <span class="sc">&gt;</span> <span class="dv">15</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_pop =</span> <span class="fu">mean</span>(Total_PopE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_W_per =</span> <span class="fu">mean</span>(perW, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_B_per =</span> <span class="fu">mean</span>(perB, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_H_per =</span> <span class="fu">mean</span>(perH, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>data_qual_B</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  `MOE_perB &gt; 15` avg_pop avg_W_per avg_B_per avg_H_per count
  &lt;lgl&gt;             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;
1 FALSE             3526.      20.6      73.2      1.11     6
2 TRUE              3705.      68.9      13.8      4.81   322
3 NA                2289.      90.2       0        2.62    31</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>data_qual_H <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(MOE_perH <span class="sc">&gt;</span> <span class="dv">15</span>) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_pop =</span> <span class="fu">mean</span>(Total_PopE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_W_per =</span> <span class="fu">mean</span>(perW, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_B_per =</span> <span class="fu">mean</span>(perB, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_H_per =</span> <span class="fu">mean</span>(perH, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>data_qual_H</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  `MOE_perH &gt; 15` avg_pop avg_W_per avg_B_per avg_H_per count
  &lt;lgl&gt;             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;
1 FALSE             2482       70.8      12.4     13.6      2
2 TRUE              3690.      69.8      13.6      4.65   342
3 NA                1212.      58.2      25.1      0       15</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>race_eth_2022 <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span> </span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">indv_MOE_cat =</span> <span class="fu">case_when</span>(MOE_perW <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">&amp;</span> MOE_perB <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">&amp;</span> MOE_perH <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">~</span> <span class="st">'All High MOE'</span>,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>                                  MOE_perW <span class="sc">&lt;</span> <span class="dv">15</span> <span class="sc">&amp;</span> MOE_perB <span class="sc">&lt;</span> <span class="dv">15</span> <span class="sc">&amp;</span> MOE_perH <span class="sc">&lt;</span> <span class="dv">15</span> <span class="sc">~</span> <span class="st">'All Low MOE'</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>                                  MOE_perW <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">&amp;</span> MOE_perB <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">|</span> MOE_perH <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">~</span> <span class="st">'Two High MOE'</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                                  MOE_perW <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">|</span> MOE_perB <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">&amp;</span> MOE_perH <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">~</span> <span class="st">'Two High MOE'</span>,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                                  MOE_perW <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">&amp;</span> MOE_perH <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">|</span> MOE_perB <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">~</span> <span class="st">'Two High MOE'</span>,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">is.na</span>(MOE_perW) <span class="sc">|</span> <span class="fu">is.na</span>(MOE_perH) <span class="sc">|</span> <span class="fu">is.na</span>(MOE_perB) <span class="sc">~</span> <span class="st">'At least one NA'</span>,</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>                                   <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">'One High MOE'</span>))</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>race_eth_2022</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 359 × 20
   GEOID       NAME   WhiteE WhiteM BlackE BlackM Hisp_LatE Hisp_LatM Total_PopE
   &lt;chr&gt;       &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1 26083000100 Kewee…   1999      6      0     11        33         4       2086
 2 26083980100 Kewee…      2      1      0     11         0        11          2
 3 26083990100 Kewee…      0     11      0     11         0        11          0
 4 26097950100 Macki…   1536    238      0     11         0        11       1594
 5 26097950200 Macki…   1858    216      0     11        49        42       2399
 6 26097950300 Macki…   1485    185      3      4        13        12       1761
 7 26097950400 Macki…   1788    187    141    107       115        59       2900
 8 26097950500 Macki…   1126    142    264    119        75        42       2189
 9 26097990000 Macki…      0     11      0     11         0        11          0
10 26125120000 Oakla…   2910    279     20     21        20        24       3074
# ℹ 349 more rows
# ℹ 11 more variables: Total_PopM &lt;dbl&gt;, perW &lt;dbl&gt;, perB &lt;dbl&gt;, perH &lt;dbl&gt;,
#   tract &lt;chr&gt;, MOE_perW &lt;dbl&gt;, MOE_perB &lt;dbl&gt;, MOE_perH &lt;dbl&gt;, MOE_cat &lt;chr&gt;,
#   MOE_catB &lt;chr&gt;, indv_MOE_cat &lt;chr&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>detail_MOE_cat <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(indv_MOE_cat) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_pop =</span> <span class="fu">mean</span>(Total_PopE, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_W_per =</span> <span class="fu">mean</span>(perW, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_B_per =</span> <span class="fu">mean</span>(perB, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">avg_H_per =</span> <span class="fu">mean</span>(perH, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">count =</span> <span class="fu">n</span>())</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>detail_MOE_cat</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  indv_MOE_cat    avg_pop avg_W_per avg_B_per avg_H_per count
  &lt;chr&gt;             &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;
1 All High MOE      3577.      58.6     21.6       5.61   165
2 At least one NA    261.      95.8      0         1.58     8
3 Two High MOE      3725.      79.0      7.12      3.71   186</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co">#just white residents having high MOE</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>race_eth_2022 <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">MOE_catW =</span> <span class="fu">ifelse</span>(MOE_perW <span class="sc">&gt;</span> <span class="dv">15</span>,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"High White MOE"</span>, <span class="st">"Low White MOE"</span>))</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>race_eth_2022<span class="sc">$</span>MOE_catW[<span class="fu">is.na</span>(race_eth_2022<span class="sc">$</span>MOE_catW)] <span class="ot">&lt;-</span> <span class="st">"No Certainty"</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>race_eth_2022</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 359 × 21
   GEOID       NAME   WhiteE WhiteM BlackE BlackM Hisp_LatE Hisp_LatM Total_PopE
   &lt;chr&gt;       &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1 26083000100 Kewee…   1999      6      0     11        33         4       2086
 2 26083980100 Kewee…      2      1      0     11         0        11          2
 3 26083990100 Kewee…      0     11      0     11         0        11          0
 4 26097950100 Macki…   1536    238      0     11         0        11       1594
 5 26097950200 Macki…   1858    216      0     11        49        42       2399
 6 26097950300 Macki…   1485    185      3      4        13        12       1761
 7 26097950400 Macki…   1788    187    141    107       115        59       2900
 8 26097950500 Macki…   1126    142    264    119        75        42       2189
 9 26097990000 Macki…      0     11      0     11         0        11          0
10 26125120000 Oakla…   2910    279     20     21        20        24       3074
# ℹ 349 more rows
# ℹ 12 more variables: Total_PopM &lt;dbl&gt;, perW &lt;dbl&gt;, perB &lt;dbl&gt;, perH &lt;dbl&gt;,
#   tract &lt;chr&gt;, MOE_perW &lt;dbl&gt;, MOE_perB &lt;dbl&gt;, MOE_perH &lt;dbl&gt;, MOE_cat &lt;chr&gt;,
#   MOE_catB &lt;chr&gt;, indv_MOE_cat &lt;chr&gt;, MOE_catW &lt;chr&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>data_qual_n_W <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(MOE_catW) <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(MOE_catW)</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>data_qual_n_W</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
# Groups:   MOE_catW [3]
  MOE_catW           n
  &lt;chr&gt;          &lt;int&gt;
1 High White MOE   187
2 Low White MOE    165
3 No Certainty       7</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#just hispanic residents having high MOE</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>race_eth_2022 <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">MOE_catH =</span> <span class="fu">ifelse</span>(MOE_perH <span class="sc">&gt;</span> <span class="dv">15</span>,</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>                          <span class="st">"High Hispanic MOE"</span>, <span class="st">"Low Hispanic MOE"</span>))</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>race_eth_2022<span class="sc">$</span>MOE_catH[<span class="fu">is.na</span>(race_eth_2022<span class="sc">$</span>MOE_catH)] <span class="ot">&lt;-</span> <span class="st">"No Certainty"</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>race_eth_2022</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 359 × 22
   GEOID       NAME   WhiteE WhiteM BlackE BlackM Hisp_LatE Hisp_LatM Total_PopE
   &lt;chr&gt;       &lt;chr&gt;   &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
 1 26083000100 Kewee…   1999      6      0     11        33         4       2086
 2 26083980100 Kewee…      2      1      0     11         0        11          2
 3 26083990100 Kewee…      0     11      0     11         0        11          0
 4 26097950100 Macki…   1536    238      0     11         0        11       1594
 5 26097950200 Macki…   1858    216      0     11        49        42       2399
 6 26097950300 Macki…   1485    185      3      4        13        12       1761
 7 26097950400 Macki…   1788    187    141    107       115        59       2900
 8 26097950500 Macki…   1126    142    264    119        75        42       2189
 9 26097990000 Macki…      0     11      0     11         0        11          0
10 26125120000 Oakla…   2910    279     20     21        20        24       3074
# ℹ 349 more rows
# ℹ 13 more variables: Total_PopM &lt;dbl&gt;, perW &lt;dbl&gt;, perB &lt;dbl&gt;, perH &lt;dbl&gt;,
#   tract &lt;chr&gt;, MOE_perW &lt;dbl&gt;, MOE_perB &lt;dbl&gt;, MOE_perH &lt;dbl&gt;, MOE_cat &lt;chr&gt;,
#   MOE_catB &lt;chr&gt;, indv_MOE_cat &lt;chr&gt;, MOE_catW &lt;chr&gt;, MOE_catH &lt;chr&gt;</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>data_qual_n_H <span class="ot">&lt;-</span> race_eth_2022 <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(MOE_catH) <span class="sc">%&gt;%</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(MOE_catH)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>data_qual_n_H</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
# Groups:   MOE_catH [3]
  MOE_catH              n
  &lt;chr&gt;             &lt;int&gt;
1 High Hispanic MOE   342
2 Low Hispanic MOE      2
3 No Certainty         15</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use group_by() and summarize() to create this comparison</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a professional table showing the patterns</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>race <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"White"</span>, <span class="st">"Black"</span>, <span class="st">"Hispanic"</span>)</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>high_MOE_n <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">187</span>, <span class="dv">322</span>, <span class="dv">342</span>)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>low_MOE_n <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">165</span>, <span class="dv">6</span>, <span class="dv">2</span>)</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>no_certain_n <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">31</span>, <span class="dv">15</span>)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>race_n_high_MOE <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(race, high_MOE_n, low_MOE_n, no_certain_n)</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>race_n_high_MOE <span class="ot">&lt;-</span> race_n_high_MOE <span class="sc">%&gt;%</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">per_High =</span> high_MOE_n<span class="sc">/</span>(high_MOE_n<span class="sc">+</span>low_MOE_n)<span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>race_n_high_MOE</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      race high_MOE_n low_MOE_n no_certain_n per_High
1    White        187       165            7 53.12500
2    Black        322         6           31 98.17073
3 Hispanic        342         2           15 99.41860</code></pre>
</div>
</div>
<p><strong>Pattern Analysis:</strong> The most stark pattern is that, whereas all three races’ population estimate overall have quite high margins of errors, this effect is significantly higher for Black and Hispanic/Latino residents. White residents have 187 tracts where the margins of error is higher than 15%, which amounts to 53.13% of all the tracts in Oakland, Mackinac, and Keweenaw counties. Black residents on the other hand have 322, which is 98.17% of all tracts, and Hispanic residents have 342, which is 99.42% of all tracts. This shows that the data for Black and Hispanic residents are much more unreliable than the data for White residents. This might either be because there are less Black and Hispanic people in these counties in general, leading to huge skews in their data depending on tracts, or because they are chronically underestimated in data collection, due to human error, bias or prejudice.</p>
</section>
</section>
<section id="part-5-policy-recommendations" class="level1">
<h1>Part 5: Policy Recommendations</h1>
<section id="analysis-integration-and-professional-summary" class="level2">
<h2 class="anchored" data-anchor-id="analysis-integration-and-professional-summary">5.1 Analysis Integration and Professional Summary</h2>
<p><strong>Your Task:</strong> Write an executive summary that integrates findings from all four analyses.</p>
<p><strong>Executive Summary Requirements:</strong></p>
<p><strong>Overall Pattern Identification</strong>: <strong>Equity Assessment</strong>: <strong>Root Cause Analysis</strong>: <strong>Strategic Recommendations</strong>:</p>
<p><strong>Executive Summary:</strong></p>
<p>Overall, my analyses shows several systematic patterns. One, smaller counties with less people generally have less reliable data. This is largely due to the fact that with smaller sample sizes, it becomes difficult to extrapolate any findings, making any statistical relationships unsure of its significance. Another pattern is soemthing briefly talked about in the previous section. Among the three counties–Oakland, Mackninac, Keweenaw–it seems that Black and Hispanic residents’ data were clearly more unreliable. This may be due to the sample size, or Black and Hispanic people don’t live in those counties, or there is something more sinister going on, where they are systematically purposefully under-counted or statistically misrepresented.</p>
<p>All of these shows that the Black and Hispanic communities are at great risk of algorithmic bias. The data technically exists, but the large margins of error make it clear that this data should be used sparingly and cautiously. Thought cautious data usage is good practice, it seems to be disadvantageous that these people of color’s data should only be used after taking further necessary precautions. This added level of difficulty in accessing and analyzing the data may lead to policy makers to intentionally not use the data either due to fear of misrepresenting their constituents or due to laziness.</p>
<p>It’s likely that Black and Hispanic people don’t live in these areas, either by change or systemic disadvantages, as seen in the case of redlining. This may lead to problems of reinforcing euro- white-centric social norms with the policies reflecting and amplifying that. The cause of both the bad data quality and bias risk may be due to human bias, where certain White surveyors might be unwilling to approach or collect data from non-White residents, consciously or not. If done subconsciously, this could lead to the belief that the data is impartial and representative, when that may not be the case.</p>
<p>There are plenty of psychology studies showing that even just acknowledging you might have bias leads to you to think through your actions more consciously and reduce personal biases. Employee workshops to increase self-awareness in such a manner might be a simple but effective technique to start address these systematic issues. Another thing to do would be to take a closer look at all the data, including other variables not just income, and across all other intersections of identities, to make sure no one get swept under the rug. Taking a closer look at the data would also reveal where there are outliers versus actual pattern. If a county seems to be an outlier in every single analyses, a closer look should be taken to try to resolve any disparities.</p>
</section>
<section id="specific-recommendations" class="level2">
<h2 class="anchored" data-anchor-id="specific-recommendations">6.3 Specific Recommendations</h2>
<p><strong>Your Task:</strong> Create a decision framework for algorithm implementation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a summary table using your county reliability data</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Include: county name, median income, MOE percentage, reliability category</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>county_reliability <span class="ot">&lt;-</span> MI_2022[,<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">7</span>,<span class="dv">8</span>)]</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>county_reliability</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 83 × 4
   NAME    med_HH_incE MOE_per reli_cat           
   &lt;chr&gt;         &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;              
 1 Alcona        50295    4.46 High Confidence    
 2 Alger         55528    5.24 Moderate Confidence
 3 Allegan       75543    3.14 High Confidence    
 4 Alpena        49133    4.31 High Confidence    
 5 Antrim        68850    4.52 High Confidence    
 6 Arenac        53487    3.77 High Confidence    
 7 Baraga        51911    5.59 Moderate Confidence
 8 Barry         75182    3.60 High Confidence    
 9 Bay           57887    4.14 High Confidence    
10 Benzie        71327    5.97 Moderate Confidence
# ℹ 73 more rows</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a new column with algorithm recommendations using case_when():</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="co"># - High Confidence: "Safe for algorithmic decisions"</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="co"># - Moderate Confidence: "Use with caution - monitor outcomes"  </span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># - Low Confidence: "Requires manual review or additional data"</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>county_reliability <span class="ot">&lt;-</span> county_reliability <span class="sc">%&gt;%</span></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">algo_rec =</span> <span class="fu">case_when</span>(reli_cat <span class="sc">==</span> <span class="st">"High Confidence"</span> <span class="sc">~</span> <span class="st">"Safe for algorithmic decisions"</span>,</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>                              reli_cat <span class="sc">==</span> <span class="st">"Moderate Confidence"</span> <span class="sc">~</span> <span class="st">"Use with caution - monitor outcomes"</span>,</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>                              reli_cat <span class="sc">==</span> <span class="st">"Low Confidence"</span> <span class="sc">~</span> <span class="st">"Requires manual review or additional data"</span>))</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Format as a professional table with kable()</span></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(county_reliability, <span class="st">"simple"</span>, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"County"</span>, <span class="st">"Median Income Estimate"</span>, <span class="st">"Margin of Error Percentage"</span>, <span class="st">"Reliability Category"</span>, <span class="st">"Algorithm Recommendation"</span>), <span class="at">caption =</span> <span class="st">"Algorithm Implementation Decision Framework"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Algorithm Implementation Decision Framework</caption>
<thead>
<tr class="header">
<th style="text-align: left;">County</th>
<th style="text-align: right;">Median Income Estimate</th>
<th style="text-align: right;">Margin of Error Percentage</th>
<th style="text-align: left;">Reliability Category</th>
<th style="text-align: left;">Algorithm Recommendation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Alcona</td>
<td style="text-align: right;">50295</td>
<td style="text-align: right;">4.4596878</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alger</td>
<td style="text-align: right;">55528</td>
<td style="text-align: right;">5.2442011</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Allegan</td>
<td style="text-align: right;">75543</td>
<td style="text-align: right;">3.1359623</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alpena</td>
<td style="text-align: right;">49133</td>
<td style="text-align: right;">4.3127837</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Antrim</td>
<td style="text-align: right;">68850</td>
<td style="text-align: right;">4.5243282</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Arenac</td>
<td style="text-align: right;">53487</td>
<td style="text-align: right;">3.7728794</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Baraga</td>
<td style="text-align: right;">51911</td>
<td style="text-align: right;">5.5941901</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Barry</td>
<td style="text-align: right;">75182</td>
<td style="text-align: right;">3.5966056</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bay</td>
<td style="text-align: right;">57887</td>
<td style="text-align: right;">4.1373711</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Benzie</td>
<td style="text-align: right;">71327</td>
<td style="text-align: right;">5.9696889</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Berrien</td>
<td style="text-align: right;">60379</td>
<td style="text-align: right;">2.6101790</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Branch</td>
<td style="text-align: right;">60600</td>
<td style="text-align: right;">3.7656766</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Calhoun</td>
<td style="text-align: right;">58191</td>
<td style="text-align: right;">2.6309910</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cass</td>
<td style="text-align: right;">65183</td>
<td style="text-align: right;">4.1222405</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Charlevoix</td>
<td style="text-align: right;">69764</td>
<td style="text-align: right;">3.4358695</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cheboygan</td>
<td style="text-align: right;">59557</td>
<td style="text-align: right;">4.0566180</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chippewa</td>
<td style="text-align: right;">58408</td>
<td style="text-align: right;">3.0766333</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Clare</td>
<td style="text-align: right;">47816</td>
<td style="text-align: right;">4.3311862</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Clinton</td>
<td style="text-align: right;">82594</td>
<td style="text-align: right;">2.7520159</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Crawford</td>
<td style="text-align: right;">57998</td>
<td style="text-align: right;">5.9346874</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Delta</td>
<td style="text-align: right;">53852</td>
<td style="text-align: right;">6.3303127</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dickinson</td>
<td style="text-align: right;">59651</td>
<td style="text-align: right;">4.3637156</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Eaton</td>
<td style="text-align: right;">77158</td>
<td style="text-align: right;">2.6089323</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Emmet</td>
<td style="text-align: right;">69690</td>
<td style="text-align: right;">5.7181805</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Genesee</td>
<td style="text-align: right;">58594</td>
<td style="text-align: right;">2.2408438</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gladwin</td>
<td style="text-align: right;">53717</td>
<td style="text-align: right;">2.7589031</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gogebic</td>
<td style="text-align: right;">47913</td>
<td style="text-align: right;">9.9471960</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Grand Traverse</td>
<td style="text-align: right;">75553</td>
<td style="text-align: right;">2.9899541</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Gratiot</td>
<td style="text-align: right;">57934</td>
<td style="text-align: right;">3.8630165</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hillsdale</td>
<td style="text-align: right;">59425</td>
<td style="text-align: right;">3.9713925</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Houghton</td>
<td style="text-align: right;">52736</td>
<td style="text-align: right;">4.8600576</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Huron</td>
<td style="text-align: right;">54475</td>
<td style="text-align: right;">2.5810005</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ingham</td>
<td style="text-align: right;">62548</td>
<td style="text-align: right;">2.9641236</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ionia</td>
<td style="text-align: right;">71720</td>
<td style="text-align: right;">3.4021194</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Iosco</td>
<td style="text-align: right;">46224</td>
<td style="text-align: right;">5.2808065</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Iron</td>
<td style="text-align: right;">52241</td>
<td style="text-align: right;">6.6805766</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Isabella</td>
<td style="text-align: right;">52638</td>
<td style="text-align: right;">4.2706790</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jackson</td>
<td style="text-align: right;">62581</td>
<td style="text-align: right;">2.5247280</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kalamazoo</td>
<td style="text-align: right;">67905</td>
<td style="text-align: right;">2.3061630</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kalkaska</td>
<td style="text-align: right;">56380</td>
<td style="text-align: right;">5.7343029</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kent</td>
<td style="text-align: right;">76247</td>
<td style="text-align: right;">1.6721969</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Keweenaw</td>
<td style="text-align: right;">55560</td>
<td style="text-align: right;">13.1407487</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lake</td>
<td style="text-align: right;">45946</td>
<td style="text-align: right;">5.1299351</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lapeer</td>
<td style="text-align: right;">75402</td>
<td style="text-align: right;">3.0556219</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Leelanau</td>
<td style="text-align: right;">82345</td>
<td style="text-align: right;">5.3202987</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lenawee</td>
<td style="text-align: right;">65484</td>
<td style="text-align: right;">2.6739356</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Livingston</td>
<td style="text-align: right;">96135</td>
<td style="text-align: right;">1.9628647</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Luce</td>
<td style="text-align: right;">51015</td>
<td style="text-align: right;">7.3350975</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mackinac</td>
<td style="text-align: right;">60620</td>
<td style="text-align: right;">5.6796437</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Macomb</td>
<td style="text-align: right;">73876</td>
<td style="text-align: right;">1.2250257</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Manistee</td>
<td style="text-align: right;">59467</td>
<td style="text-align: right;">4.3217247</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Marquette</td>
<td style="text-align: right;">63115</td>
<td style="text-align: right;">4.0133090</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mason</td>
<td style="text-align: right;">60744</td>
<td style="text-align: right;">3.7024233</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mecosta</td>
<td style="text-align: right;">54132</td>
<td style="text-align: right;">5.8763763</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Menominee</td>
<td style="text-align: right;">54074</td>
<td style="text-align: right;">5.3870622</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Midland</td>
<td style="text-align: right;">73643</td>
<td style="text-align: right;">4.3615822</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Missaukee</td>
<td style="text-align: right;">57667</td>
<td style="text-align: right;">6.6051641</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Monroe</td>
<td style="text-align: right;">72573</td>
<td style="text-align: right;">2.7930498</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Montcalm</td>
<td style="text-align: right;">61250</td>
<td style="text-align: right;">3.8742857</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Montmorency</td>
<td style="text-align: right;">46345</td>
<td style="text-align: right;">8.1907433</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Muskegon</td>
<td style="text-align: right;">61347</td>
<td style="text-align: right;">2.1810357</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Newaygo</td>
<td style="text-align: right;">59065</td>
<td style="text-align: right;">3.1558453</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Oakland</td>
<td style="text-align: right;">92620</td>
<td style="text-align: right;">1.0289354</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oceana</td>
<td style="text-align: right;">60691</td>
<td style="text-align: right;">4.9315384</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ogemaw</td>
<td style="text-align: right;">50377</td>
<td style="text-align: right;">4.9189114</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ontonagon</td>
<td style="text-align: right;">48316</td>
<td style="text-align: right;">7.9559566</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Osceola</td>
<td style="text-align: right;">54875</td>
<td style="text-align: right;">3.8159453</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Oscoda</td>
<td style="text-align: right;">48692</td>
<td style="text-align: right;">5.3006654</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Otsego</td>
<td style="text-align: right;">62865</td>
<td style="text-align: right;">9.4010976</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ottawa</td>
<td style="text-align: right;">83932</td>
<td style="text-align: right;">2.1791450</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Presque Isle</td>
<td style="text-align: right;">55986</td>
<td style="text-align: right;">6.3730218</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="even">
<td style="text-align: left;">Roscommon</td>
<td style="text-align: right;">49898</td>
<td style="text-align: right;">6.2567638</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Saginaw</td>
<td style="text-align: right;">56579</td>
<td style="text-align: right;">2.4832535</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">St.&nbsp;Clair</td>
<td style="text-align: right;">66887</td>
<td style="text-align: right;">2.5819666</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">St.&nbsp;Joseph</td>
<td style="text-align: right;">62281</td>
<td style="text-align: right;">2.6348325</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sanilac</td>
<td style="text-align: right;">55740</td>
<td style="text-align: right;">3.9415142</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Schoolcraft</td>
<td style="text-align: right;">55071</td>
<td style="text-align: right;">11.4906212</td>
<td style="text-align: left;">Low Confidence</td>
<td style="text-align: left;">Requires manual review or additional data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Shiawassee</td>
<td style="text-align: right;">62498</td>
<td style="text-align: right;">4.5153445</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tuscola</td>
<td style="text-align: right;">59815</td>
<td style="text-align: right;">3.1563989</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Van Buren</td>
<td style="text-align: right;">65531</td>
<td style="text-align: right;">5.1822801</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Washtenaw</td>
<td style="text-align: right;">84245</td>
<td style="text-align: right;">2.7977922</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wayne</td>
<td style="text-align: right;">57223</td>
<td style="text-align: right;">0.9838701</td>
<td style="text-align: left;">High Confidence</td>
<td style="text-align: left;">Safe for algorithmic decisions</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Wexford</td>
<td style="text-align: right;">58652</td>
<td style="text-align: right;">5.8071336</td>
<td style="text-align: left;">Moderate Confidence</td>
<td style="text-align: left;">Use with caution - monitor outcomes</td>
</tr>
</tbody>
</table>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>safe_data_counties <span class="ot">&lt;-</span> county_reliability <span class="sc">%&gt;%</span> <span class="fu">filter</span>(algo_rec <span class="sc">==</span> <span class="st">"Safe for algorithmic decisions"</span>)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>cautious_data_counties <span class="ot">&lt;-</span> county_reliability <span class="sc">%&gt;%</span> <span class="fu">filter</span>(algo_rec <span class="sc">==</span> <span class="st">"Use with caution - monitor outcomes"</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>need_more_data_counties <span class="ot">&lt;-</span> county_reliability <span class="sc">%&gt;%</span> <span class="fu">filter</span>(algo_rec <span class="sc">==</span> <span class="st">"Requires manual review or additional data"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Key Recommendations:</strong></p>
<p><strong>Your Task:</strong> Use your analysis results to provide specific guidance to the department.</p>
<ol type="1">
<li><strong>Counties suitable for immediate algorithmic implementation:</strong></li>
</ol>
<p>[1] “Alcona” “Allegan” “Alpena” “Antrim” “Arenac”<br>
[6] “Barry” “Bay” “Berrien” “Branch” “Calhoun”<br>
[11] “Cass” “Charlevoix” “Cheboygan” “Chippewa” “Clare”<br>
[16] “Clinton” “Dickinson” “Eaton” “Genesee” “Gladwin”<br>
[21] “Grand Traverse” “Gratiot” “Hillsdale” “Houghton” “Huron”<br>
[26] “Ingham” “Ionia” “Isabella” “Jackson” “Kalamazoo”<br>
[31] “Kent” “Lapeer” “Lenawee” “Livingston” “Macomb”<br>
[36] “Manistee” “Marquette” “Mason” “Midland” “Monroe”<br>
[41] “Montcalm” “Muskegon” “Newaygo” “Oakland” “Oceana”<br>
[46] “Ogemaw” “Osceola” “Ottawa” “Saginaw” “St.&nbsp;Clair”<br>
[51] “St.&nbsp;Joseph” “Sanilac” “Shiawassee” “Tuscola” “Washtenaw”<br>
[56] “Wayne”</p>
<ol start="2" type="1">
<li><strong>Counties requiring additional oversight:</strong></li>
</ol>
<p>[1] “Alger” “Baraga” “Benzie” “Crawford” “Delta” “Emmet”<br>
[7] “Gogebic” “Iosco” “Iron” “Kalkaska” “Lake” “Leelanau”<br>
[13] “Luce” “Mackinac” “Mecosta” “Menominee” “Missaukee” “Montmorency” [19] “Ontonagon” “Oscoda” “Otsego” “Presque Isle” “Roscommon” “Van Buren”<br>
[25] “Wexford”</p>
<p>These are counties where we are moderately confident in the data of. The data isn’t to be used without monitoring the results for unusual patterns or distributions. If there are odd results, they should be examined more closely to see what may have caused the outlier. These data should also be examined to see what shape the raw data forms, before conducting any analysis. If the distribution, skew or peaks look abnormal, or there are too many outliers, that county may not be used to that specific analysis. Judgments should be made on a case-to-case basis.</p>
<ol start="3" type="1">
<li><strong>Counties needing alternative approaches:</strong></li>
</ol>
<p>[1] “Keweenaw” “Schoolcraft”</p>
<p>There are only two counties in Michigan where we are not confident in the reliability of the data at all, and more data from these counties should be collected if possible. First, we should try to find out why these two counties were specifically unreliable in data, such as examining the sample size. As seen in earlier analysis, these counties are in the top 5 smallest counties in Michigan, which may definitely cause the unreliability. In this case, we should go out of our way to collect more data from this county to ensure the data becomes more reliable, as the ACS is a sample and more data can be collected. If this doesn’t work, perhaps we should consider merging these counties with neighboring counties, especially if there are no major differences between the two areas. If there are massive differences, then maybe we should take a closer look at these counties in general to see why such disparities happen, and work on ameliorating that.</p>
</section>
<section id="questions-for-further-investigation" class="level2">
<h2 class="anchored" data-anchor-id="questions-for-further-investigation">Questions for Further Investigation</h2>
<p>[List 2-3 questions that your analysis raised that you’d like to explore further in future assignments. Consider questions about spatial patterns, time trends, or other demographic factors.]</p>
<ol type="1">
<li><p>How does data unreliability change as we look at different data?</p></li>
<li><p>Is sample size the biggest factor in swaying reliability, or is there something else, and can that be examined by looking at differences between different data?</p></li>
<li><p>In Michigan, there are ethnic enclaves (Japanese, Chinese, Korean, Middle Eastern) which the 3 races in these analyses don’t cover. How would including those change the analyses done here today?</p></li>
</ol>
</section>
</section>
<section id="technical-notes" class="level1">
<h1>Technical Notes</h1>
<p><strong>Data Sources:</strong> - U.S. Census Bureau, American Community Survey 2018-2022 5-Year Estimates - Retrieved via tidycensus R package on [date]</p>
<p><strong>Reproducibility:</strong> - All analysis conducted in R version [your version] - Census API key required for replication - Complete code and documentation available at: [your portfolio URL]</p>
<p><strong>Methodology Notes:</strong> In 4.2, the last question, I manually inputted the table data, instead of using reproducible variables.</p>
<p><strong>Limitations:</strong> [Note any limitations in your analysis - sample size issues, geographic scope, temporal factors, etc.]</p>
<hr>
<section id="submission-checklist" class="level2">
<h2 class="anchored" data-anchor-id="submission-checklist">Submission Checklist</h2>
<p>Before submitting your portfolio link on Canvas:</p>
<ul class="task-list">
<li><label><input type="checkbox">All code chunks run without errors</label></li>
<li><label><input type="checkbox">All “[Fill this in]” prompts have been completed</label></li>
<li><label><input type="checkbox">Tables are properly formatted and readable</label></li>
<li><label><input type="checkbox">Executive summary addresses all four required components</label></li>
<li><label><input type="checkbox">Portfolio navigation includes this assignment</label></li>
<li><label><input type="checkbox">Census API key is properly set</label></li>
<li><label><input type="checkbox">Document renders correctly to HTML</label></li>
</ul>
<p><strong>Remember:</strong> Submit your portfolio URL on Canvas, not the file itself. Your assignment should be accessible at <code>your-portfolio-url/labs/lab_1/your_file_name.html</code></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>